"""
Django settings for accounts project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# ============================================================
# GOOGLE DRIVE CONFIGURATION
# ============================================================
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET')
GOOGLE_REFRESH_TOKEN = os.environ.get('GOOGLE_REFRESH_TOKEN')
GOOGLE_DRIVE_PARENT_FOLDER_ID = os.environ.get('GOOGLE_DRIVE_PARENT_FOLDER_ID')
GOOGLE_DRIVE_BASE_FOLDER = os.environ.get('GOOGLE_DRIVE_BASE_FOLDER', 'JUSTIFICATION VOUCHER PDF')

# Validate
if not all([GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REFRESH_TOKEN, GOOGLE_DRIVE_PARENT_FOLDER_ID]):
    print("⚠️  Warning: Google Drive credentials not fully configured")
else:
    print("✅ Google Drive credentials loaded")

# ============================================================
# SECURITY SETTINGS
# ============================================================
SECRET_KEY = 'django-insecure-m)wqx^^f)o#wwc8kek#@20!juq7gzob8#s2ux9jt^8td5jqfa1'
DEBUG = True
ALLOWED_HOSTS = ['*']
AUTH_USER_MODEL = 'banklist.User'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# APPLICATION DEFINITION
# ============================================================
INSTALLED_APPS = [
    'banklist',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # # Celery Apps (NEW)
    'django_celery_beat',
    'django_celery_results',


]

# ============================================================
# REST FRAMEWORK CONFIGURATION
# ============================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# ============================================================
# JWT CONFIGURATION
# ============================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ============================================================
# MIDDLEWARE
# ============================================================
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ============================================================
# CORS CONFIGURATION
# ============================================================
CORS_ALLOWED_ORIGINS = [
    "http://192.168.1.41:5173",
    "http://192.168.1.6:5173",
    "http://localhost:5173",
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True

# ============================================================
# URLS & TEMPLATES
# ============================================================
ROOT_URLCONF = 'accounts.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accounts.wsgi.application'

# ============================================================
# DATABASE CONFIGURATION
# ============================================================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "accountbanklist",
        "USER": "bariflo",
        "PASSWORD": "Bariflo@2401",
        "HOST": "192.168.1.199",
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}

# ============================================================
# REDIS & CACHE CONFIGURATION
# ============================================================
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")

# ============================================================
# OLLAMA EXTRACTION FALLBACK
# ============================================================
OLLAMA_ENABLED = os.environ.get("OLLAMA_ENABLED", "true").lower() == "true"
OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://127.0.0.1:11434")
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.1:8b")
OLLAMA_TIMEOUT = int(os.environ.get("OLLAMA_TIMEOUT", 120))

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "KEY_PREFIX": "accounts_dashboard",
        "TIMEOUT": int(os.environ.get("CACHE_DEFAULT_TIMEOUT", 60)),
    }
}

# ============================================================
# CELERY CONFIGURATION (UPDATED)
# ============================================================
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", REDIS_URL)

# Celery Content Settings
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = True

# Celery Results (NEW)
CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_RESULT_EXPIRES = 86400  # 1 day

# Celery Beat (Scheduled Tasks) - NEW
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Celery Task Queues (NEW)
CELERY_TASK_QUEUES = {
    'default': {'exchange': 'default', 'binding_key': 'default'},
    'parsing': {'exchange': 'parsing', 'binding_key': 'parsing'},
    'reconciliation': {'exchange': 'reconciliation', 'binding_key': 'reconciliation'},
}

# Celery Task Routing (NEW)
CELERY_TASK_ROUTES = {
    'banklist.tasks.parse_statement_task': {'queue': 'parsing'},
    'banklist.tasks.process_receipt_task': {'queue': 'parsing'},
    'banklist.tasks.run_reconciliation_task': {'queue': 'reconciliation'},
    'banklist.tasks.*': {'queue': 'default'},
}

# Celery Rate Limiting (NEW)
CELERY_TASK_ANNOTATIONS = {
    'banklist.tasks.parse_statement_task': {'rate_limit': '10/m'},
    'banklist.tasks.process_receipt_task': {'rate_limit': '20/m'},
    'banklist.tasks.run_reconciliation_task': {'rate_limit': '2/m'},
}

# Celery Time Limits (NEW)
CELERY_TASK_TIME_LIMIT = 3600  # 1 hour max runtime
CELERY_TASK_SOFT_TIME_LIMIT = 3000  # 50 minutes soft limit

# Celery Worker Settings (NEW)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100

# ============================================================
# PASSWORD VALIDATION
# ============================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ============================================================
# INTERNATIONALIZATION
# ============================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'  # Changed from UTC
USE_I18N = True
USE_TZ = True

# ============================================================
# STATIC FILES
# ============================================================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ============================================================
# LOGGING CONFIGURATION (NEW)
# ============================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
        'celery_file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'celery.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'banklist': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'celery': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery.task': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
LOG_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# ============================================================
# EMAIL CONFIGURATION (Optional - for notifications)
# ============================================================
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@example.com')

# ============================================================
# CUSTOM SETTINGS
# ============================================================
# Maximum file upload size (10MB)
MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# Reconciliation settings
RECONCILIATION_AUTO_MATCH = True
RECONCILIATION_DEFAULT_TOLERANCE = 0.01
RECONCILIATION_DATE_TOLERANCE_DAYS = 3

# Receipt extraction settings
RECEIPT_OCR_ENABLED = True
RECEIPT_OCR_LANGUAGE = 'eng'
RECEIPT_CONFIDENCE_THRESHOLD = 70

# Statement parsing settings
STATEMENT_PARSE_TIMEOUT = 60  # seconds
