# Generated by Django 5.2.15 on 2026-06-28 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0002_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('bank_detected', models.CharField(blank=True, max_length=50)),
                ('parsed', models.BooleanField(default=False)),
                ('parse_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='banklist.bankaccount')),
            ],
            options={
                'db_table': 'uploaded_statements',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField()),
                ('value_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ref_no', models.CharField(blank=True, max_length=255)),
                ('utr_no', models.CharField(blank=True, max_length=100)),
                ('txn_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('reconcile_status', models.CharField(choices=[('matched', 'Matched'), ('unmatched', 'Unmatched'), ('receipt_missing', 'Receipt Missing'), ('ignored', 'Ignored')], default='unmatched', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banklist.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banklist.company')),
                ('matched_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_by', to='banklist.transaction')),
                ('statement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banklist.uploadedstatement')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['txn_date'],
                'indexes': [models.Index(fields=['bank_account', 'txn_date'], name='transaction_bank_ac_dde8dc_idx'), models.Index(fields=['utr_no'], name='transaction_utr_no_3c332e_idx'), models.Index(fields=['reconcile_status'], name='transaction_reconci_36dab8_idx')],
            },
        ),
    ]
