# Generated by Django 5.2.15 on 2026-07-03 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0004_receiptdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('UPLOAD_STATEMENT', 'Upload Statement'), ('UPLOAD_RECEIPT', 'Upload Receipt'), ('RUN_RECONCILIATION', 'Run Reconciliation'), ('AUTO_MATCH', 'Auto Match'), ('MANUAL_MATCH', 'Manual Match'), ('UNMATCH', 'Unmatch'), ('UPDATE_STATUS', 'Update Status'), ('DELETE_TRANSACTION', 'Delete Transaction'), ('CLEAR_ALL_DATA', 'Clear All Data'), ('RESET_FILTERS', 'Reset Filters'), ('SYNC_RECEIPTS', 'Sync Receipts'), ('PARSE_STATEMENT', 'Parse Statement')], max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Rules', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('match_by_amount', models.BooleanField(default=True)),
                ('amount_tolerance', models.DecimalField(decimal_places=2, default=0.01, max_digits=5)),
                ('match_by_date', models.BooleanField(default=True)),
                ('date_tolerance_days', models.IntegerField(default=3)),
                ('match_by_utr', models.BooleanField(default=True)),
                ('match_by_description', models.BooleanField(default=False)),
                ('description_similarity_threshold', models.FloatField(default=0.8)),
                ('auto_match_on_upload', models.BooleanField(default=False)),
                ('require_receipt_above_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reconciliation_rules',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('matched_count', models.IntegerField(default=0)),
                ('receipt_missing_count', models.IntegerField(default=0)),
                ('unmatched_count', models.IntegerField(default=0)),
                ('ignored_count', models.IntegerField(default=0)),
                ('match_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('run_time_seconds', models.FloatField(default=0)),
                ('is_auto', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reconciliation_runs',
                'ordering': ['-run_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='receiptdocument',
            new_name='receipt_doc_company_5c7808_idx',
            old_name='receipt_doc_company_8f6d16_idx',
        ),
        migrations.RenameIndex(
            model_name='receiptdocument',
            new_name='receipt_doc_receipt_0b93c4_idx',
            old_name='receipt_doc_receipt_1fcb9f_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='banklist.company'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_rules', to='banklist.company'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='bank_account_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs_as_first', to='banklist.bankaccount'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='bank_account_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs_as_second', to='banklist.bankaccount'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_runs', to='banklist.company'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='run_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'action'], name='audit_logs_company_86928e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
    ]
