# Generated by Django 5.2.15 on 2026-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0005_auditlog_reconciliationrule_reconciliationrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
