# Generated by Django 5.2.15 on 2026-07-28 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0006_alter_transaction_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptdocument',
            name='matched_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_receipts', to='banklist.transaction'),
        ),
    ]
