# Generated by Django 5.2.15 on 2026-08-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0008_particular_transaction_accounting_particular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounting_particular',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='accounting_particular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='banklist.accountingparticular'),
        ),
    ]
