# Generated by Django 5.2.15 on 2026-08-12 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0009_accountingparticular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='banklist.company')),
            ],
            options={
                'db_table': 'grants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternalTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_transfers', to='banklist.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionFundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocation_type', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_allocations', to='banklist.grant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fund_allocations', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_allocations', to='banklist.transaction')),
            ],
            options={
                'db_table': 'transaction_fund_allocations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='grant',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_grant_per_company'),
        ),
        migrations.AddConstraint(
            model_name='transactionfundallocation',
            constraint=models.UniqueConstraint(fields=('transaction', 'agency', 'allocation_type'), name='unique_transaction_agency_allocation'),
        ),
    ]
