# Generated by Django 5.2.15 on 2026-08-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0010_grant_internaltransfer_transactionfundallocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'funds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'GrantMaster',
                'ordering': ['grant_name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='transactionfundallocation',
            name='unique_transaction_agency_allocation',
        ),
        migrations.RemoveField(
            model_name='transactionfundallocation',
            name='agency',
        ),
        migrations.AddField(
            model_name='fund',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='banklist.grant'),
        ),
        migrations.AddField(
            model_name='fund',
            name='source_transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='created_fund', to='banklist.transaction'),
        ),
        migrations.AddField(
            model_name='transactionfundallocation',
            name='fund',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_allocations', to='banklist.fund'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='transactionfundallocation',
            constraint=models.UniqueConstraint(fields=('transaction', 'fund', 'allocation_type'), name='unique_transaction_fund_allocation'),
        ),
        migrations.AddConstraint(
            model_name='grantmaster',
            constraint=models.UniqueConstraint(fields=('grant_name',), name='unique_grant_name'),
        ),
        migrations.AddField(
            model_name='grant',
            name='grant_master',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='company_grants', to='banklist.grantmaster'),
            preserve_default=False,
        ),
    ]
