# Generated by Django 5.2.15 on 2026-08-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0011_fund_grantmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='fund',
            constraint=models.UniqueConstraint(fields=('grant', 'name'), name='unique_fund_name_per_grant'),
        ),
    ]
