# Generated by Django 5.2.15 on 2026-08-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0012_fund_name_fund_unique_fund_name_per_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalTransferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internal_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_transactions', to='banklist.internaltransfer')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='internal_transfer_transaction', to='banklist.transaction')),
            ],
            options={
                'db_table': 'internal_transfer_transactions',
                'constraints': [models.UniqueConstraint(fields=('internal_transfer', 'role'), name='unique_internal_transfer_role')],
            },
        ),
    ]
