# Generated by Django 5.2.15 on 2026-08-25 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0013_internaltransfertransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_strategy', models.CharField(choices=[('TABLE', 'Table'), ('COORDINATE', 'Coordinate'), ('OCR', 'OCR')], max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statement_config', to='banklist.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankStatementFieldAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('date', 'Date'), ('narration', 'Narration'), ('ref_no', 'Reference Number'), ('value_date', 'Value Date'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('balance', 'Balance')], max_length=50)),
                ('alias', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_aliases', to='banklist.bankstatementconfig')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('config', 'field_name', 'alias'), name='unique_bank_statement_field_alias')],
            },
        ),
    ]
