# Generated by Django 5.2.15 on 2026-08-27 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0014_bankstatementconfig_bankstatementfieldalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='grant_master',
        ),
        migrations.AddField(
            model_name='grant',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agencies',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_agency_name')],
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='agency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='banklist.agency'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TransactionGrantAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocation_type', models.CharField(choices=[('source', 'Source'), ('destination', 'Destination')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grant_allocations', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_allocations', to='banklist.grant')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_allocations', to='banklist.transaction')),
            ],
            options={
                'db_table': 'transaction_grant_allocations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('transaction', 'grant', 'allocation_type'), name='unique_transaction_grant_allocation')],
            },
        ),
    ]
