# Generated by Django 5.2.15 on 2026-08-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0015_remove_grant_grant_master_grant_amount_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
