# Generated by Django 5.2.15 on 2026-08-27 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0016_grant_end_date_grant_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='GrantMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='grant_milestones/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='banklist.grant')),
            ],
            options={
                'db_table': 'grant_milestones',
                'ordering': ['start_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GrantTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_name', models.CharField(max_length=255)),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document_information', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='grant_transactions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_transactions', to='banklist.grant')),
            ],
            options={
                'db_table': 'grant_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
