# Generated by Django 5.2.15 on 2026-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banklist', '0017_grant_status_grantmilestone_granttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
