from django.urls import path
from .views import (
    search_banks,
    register,
    login,
    logout,
    list_bank_accounts,
    delete_bank_account,
    init_company_folder,
    create_drive_folder,
    create_drive_folder_async,
    upload_to_drive,
    upload_to_drive_async,
    task_status,
    upload_receipt,
    sync_receipt_folder,
    list_receipts,
    extract_receipts,
    parse_statement,
    list_transactions,
    run_reconciliation_view,
    reconciliation_stats,
    list_statements,
    # ========== NEW IMPORTS FOR RECONCILIATION ==========
    dashboard_summary,
    run_full_reconciliation_view,
    match_receipts_view,
    reconciliation_history,
    get_audit_log,
    clear_all_data,
    run_full_reconciliation_v2,
    transaction_management,
    particular_list,
    update_transaction,
    cash_flow_analysis,
    accounting_particular_list, transaction_journey,
    # create_grant,
    assign_credit_to_grant,
    # list_grant_masters,
    # grant_master_detail,
    get_transaction_receipt_info,
    get_company_grants,
    # get_available_funds_for_transaction,
    # assign_funds_to_debit, 
    get_bank_grants_funds,
    get_fund_tracker,
    # get_all_bank_grants_funds,
    upload_transaction_receipt,
    list_agency,
    create_grant,
    create_agency,
    get_agencies_with_grants,
    get_available_grants_for_transaction,
    assign_grants_to_debit,
    get_all_bank_grants,
    grant_wise_outflow,
    get_transaction_movement_info,
    download_grant_wise_outflow
)

from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    # Auth URLs
    path('auth/register/', register, name='register'),
    path('auth/login/', login, name='login'),
    path('auth/logout/', logout, name='logout'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # Bank URLs
    path('banks/search/', search_banks, name='search_banks'),
    path('bank-accounts/', list_bank_accounts, name='list_bank_accounts'),
    path('bank-accounts/<int:account_id>/delete/', delete_bank_account, name='delete_bank_account'),
    path('banks/init-company-folder/', init_company_folder, name='init_company_folder'),
    path('banks/create-folder/', create_drive_folder, name='create_drive_folder'),
    path('banks/create-folder/async/', create_drive_folder_async, name='create_drive_folder_async'),
    path('banks/upload-file/', upload_to_drive, name='upload_to_drive'),
    path('banks/upload-file/async/', upload_to_drive_async, name='upload_to_drive_async'),
    path('tasks/<str:task_id>/status/', task_status, name='task_status'),
    
    # Receipt URLs
    path('receipts/upload/', upload_receipt, name='upload_receipt'),
    path('receipts/sync-folder/', sync_receipt_folder, name='sync_receipt_folder'),
    path('receipts/list/', list_receipts, name='list_receipts'),
    path('receipts/extract/', extract_receipts, name='extract_receipts'),
    
    # Reconciliation URLs (Existing)
    path('reconciliation/parse-statement/', parse_statement, name='parse_statement'),
    path('reconciliation/transactions/', list_transactions, name='list_transactions'),
    path('reconciliation/run/', run_reconciliation_view, name='run_reconciliation'),
    path('reconciliation/stats/', reconciliation_stats, name='reconciliation_stats'),
    path('reconciliation/statements/', list_statements, name='list_statements'),
    
    # ========== NEW RECONCILIATION URLs ==========
    path('reconciliation/dashboard-summary/', dashboard_summary, name='dashboard-summary'),
    path('reconciliation/run-full/', run_full_reconciliation_view, name='run-full-reconciliation'),
    path('reconciliation/match-receipts/', match_receipts_view, name='match-receipts'),
    path('reconciliation/history/', reconciliation_history, name='reconciliation-history'),
    path('reconciliation/audit-log/', get_audit_log, name='audit-log'),
    path('reconciliation/clear-all/', clear_all_data, name='clear-all-data'),




    path("reconciliation/run-v2/", run_full_reconciliation_v2, name="run_full_reconciliation_v2",),
    path("reconcilation/transaction-management/", transaction_management, name="transaction-management"),
    path("particulars/",particular_list,name="particular-list"),
    path("accounting-particulars/",accounting_particular_list,name="accounting-particular-dropdown"),
    path("transactions/<int:pk>/",update_transaction,name="update-transaction"),
    path("reports/cash-flow/",cash_flow_analysis,name="cash-flow-analysis"),
    path("transactions/<int:pk>/journey/",transaction_journey,name="transaction_journey"),
    path("agencies/",list_agency,name='list-agency'),
    path("agencies/create/",create_agency,name='create-agency'),
    # path('grant-masters/<int:grant_master_id>/',grant_master_detail,name='grant-master-detail'),
    path('grants/create/',create_grant,name='create-grant'),
    path('agencies/grants/',get_agencies_with_grants,name='get-agencies-with-grants'),
    path('transactions/<int:transaction_id>/assign-grant/',assign_credit_to_grant,name='assign-credit-to-grant'),
    path('transactions/<int:transaction_id>/receipt-info/',get_transaction_receipt_info,name='transaction-receipt-info'),
    path('grants/',get_company_grants,name='get-company-grants'), 
    # path('transactions/<int:transaction_id>/available-funds/',get_available_funds_for_transaction,name='get-available-funds-for-transaction'),
    path('transactions/<int:transaction_id>/available-grants/',get_available_grants_for_transaction,name='get-available-grants-for-transaction'),
    # path('transactions/<int:transaction_id>/assign-funds/',assign_funds_to_debit,name='assign-funds-to-debit'),
    path('transactions/<int:transaction_id>/assign-grants/',assign_grants_to_debit,name='assign-grants-to-debit'),
    path('bank-accounts/<int:bank_account_id>/funds/',get_bank_grants_funds,name='get-bank-grants-funds'),
    # path('bank-accounts/funds/',get_all_bank_grants_funds,name='get-all-bank-grants-funds'),
    path('bank-accounts/grants/',get_all_bank_grants,name='get-all-bank-grants'),
    path('funds/<int:fund_id>/tracker/',get_fund_tracker,name='get-fund-tracker'),
    path('grant-wise-outflow/',grant_wise_outflow,name='grant-wise-outflow'),
    path('grant-wise-outflow/download/',download_grant_wise_outflow,name='download-grant-wise-outflow'),
    path('transactions/<int:transaction_id>/receipts/',upload_transaction_receipt,name='upload-transaction-receipt'),
    path('transaction/<int:transaction_id>/movement-info/',get_transaction_movement_info,name='transaction-movement-info')
]